name: Fetch AI News Updates

on:
  schedule:
    - cron: '0 */12 * * *'  # Runs every 12 hours
  workflow_dispatch:  # Allows manual triggering

jobs:
  fetch-news-updates:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4  # Updated from v3 to v4

    - name: Set up Python
      uses: actions/setup-python@v5  # Updated from v4 to v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run AI news scanner
      run: python ai_news_scanner.py
      
    - name: Commit and push if there are changes
      run: |
        git config --global user.name 'GitHub Action'
        git config --global user.email 'action@github.com'
        git add ai_news_updates.txt
        git diff --quiet && git diff --staged --quiet || (git commit -m "Update AI news" && git push)

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: ai-news-updates
        path: ai_news_updates.txt

    - name: Output Python version and pip list
      if: always()  # This will run regardless of previous step outcomes
      run: |
        python --version
        pip list

    - name: Debug on failure
      if: failure()
      run: |
        echo "Workflow failed. Outputting additional debug information:"
        ls -la
        cat ai_news_updates.txt || echo "ai_news_updates.txt not found"
        git status
